#Extracting to top level variables because including in a dictionary prevents these "plugin" variables 
centos7_iso_url: "{{ artifact_server }}/iso/CentOS-7-x86_64-Everything-2003.iso"
centos7_mac_address: "{{ '00:50:56:A8' | random_mac }}"
centos7_ssh_username: sysadmin
centos7_ssh_password: BadPassword1234$
centos7_ssh_privkey_path: "{{ playbook_dir }}/../insecure_ssh_key/id_rsa"
centos7_ssh_pubkey_path: "{{ playbook_dir }}/../insecure_ssh_key/id_rsa.pub"
centos7_ssh_pubkey: "{{ lookup('file', centos7_ssh_pubkey_path) }}"
centos7_vm_name: centos7
centos7_files:
- src: centos7/ks.cfg
  dest: centos7/ks.cfg
- src: centos7/playbook.yml
  dest: centos7/playbook.yml

#Build the Packer file
centos7_packer_file:
  variables:
    password: !unsafe '{{ env `VMWARE_PASSWORD` }}'
    rhsm_password: !unsafe '{{ env `RHSM_PASSWORD` }}'
  sensitive-variables:
  - password
  - rhsm_password
  builders:
  - type: vsphere-iso
    name: centos7_vsphere_iso
    convert_to_template: true
    CPUs: 2
    RAM: 4096
    RAM_reserve_all: true
    username: "{{ vsphere.username }}"
    password: !unsafe '{{ user `password` }}'
    vcenter_server: "{{ vsphere.vcenter_server }}"
    cluster: "{{ vsphere.cluster }}"
    datacenter: "{{ vsphere.datacenter }}"
    datastore: "{{ vsphere.datastore }}"
    folder: "{{ vsphere.folder }}"
    disk_controller_type: pvscsi
    firmware: bios
    floppy_files:
    - centos7/ks.cfg
    boot_wait: 10s
    boot_order: disk,cdrom,floppy
    boot_command:
    - <esc><wait>
    - linux ks=hd:fd0:/ks.cfg<enter>
    guest_os_type: centos7_64guest
    insecure_connection: "true"
    iso_checksum: none
    iso_urls:
    - "{{ centos7_iso_url }}"
    network_adapters:
      - network: "{{ vsphere.network }}"
        mac_address: "{{ centos7_mac_address }}"
        network_card: vmxnet3
    vm_name: "{{ centos7_vm_name }}"
    ssh_username: "{{ centos7_ssh_username }}"
    ssh_private_key_file: "{{ centos7_ssh_privkey_path }}" 
    notes: "SSH Username {{ centos7_ssh_username }}\nSSH Password {{ centos7_ssh_password }}"
    storage:
      - disk_size: 40906
        disk_thin_provisioned: true
  provisioners:
  - type: ansible
    playbook_file: centos7/playbook.yml
    extra_arguments:
    - --extra-vars
    - "rhsm_username={{ rhsm.username }} rhsm_password={{ rhsm.password }} rhsm_pool_id={{ rhsm.pool_id }}"
    user: "{{ centos7_ssh_username }}"
    ansible_env_vars:
    - ANSIBLE_HOST_KEY_CHECKING=False
    ssh_authorized_key_file: "{{ centos7_ssh_pubkey_path }}"
    use_proxy: false
    only:
    - centos7_vsphere_iso
