rhel8_iso_url: "{{ artifact_server }}/iso/rhel-8.2-x86_64-dvd.iso"
rhel8_mac_address: "{{ '00:50:56:A8' | random_mac }}"
rhel8_ssh_username: sysadmin
rhel8_ssh_password: BadPassword1234$
rhel8_ssh_privkey_path: "{{ playbook_dir }}/../insecure_ssh_key/id_rsa"
rhel8_ssh_pubkey_path: "{{ playbook_dir }}/../insecure_ssh_key/id_rsa.pub"
rhel8_ssh_pubkey: "{{ lookup('file', rhel8_ssh_pubkey_path) }}"
rhel8_vm_name: rhel8
rhel8_files:
- src: rhel8/ks.cfg
  dest: rhel8/ks.cfg
- src: rhel8/playbook.yml
  dest: rhel8/playbook.yml

rhel8_packer_file:
  variables:
    password: !unsafe '{{ env `VMWARE_PASSWORD` }}'
    rhsm_password: !unsafe '{{ env `RHSM_PASSWORD` }}'
  sensitive-variables:
  - password
  - rhsm_password
  builders:
  - type: vsphere-iso
    name: rhel8_vsphere_iso
    convert_to_template: true
    CPUs: 2
    RAM: 4096
    RAM_reserve_all: true
    username: "{{ vsphere.username }}"
    password: !unsafe '{{ user `password` }}'
    vcenter_server: "{{ vsphere.vcenter_server }}"
    cluster: "{{ vsphere.cluster }}" 
    datacenter: "{{ vsphere.datacenter }}"
    datastore: "{{ vsphere.datastore }}"
    folder: "{{ vsphere.folder }}"
    disk_controller_type: pvscsi
    firmware: bios
    boot_wait: 10s
    boot_order: disk,cdrom
    http_directory: rhel8
    boot_command:
    - !unsafe '<tab> inst.sshd inst.text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort}}/ks.cfg<enter><wait>'
    guest_os_type: centos7_64guest
    insecure_connection: "true"
    iso_checksum: none
    iso_urls:
    - "{{ rhel8_iso_url }}"
    network_adapters:
    - network: "{{ vsphere.network }}"
      mac_address: "{{ rhel8_mac_address }}"
      network_card: vmxnet3
    vm_name: "{{ rhel8_vm_name }}"
    ssh_username: "{{ rhel8_ssh_username }}"
    ssh_private_key_file: "{{ rhel8_ssh_privkey_path }}" 
    notes: "SSH Username {{ rhel8_ssh_username }}\nSSH Password {{ rhel8_ssh_password }}"
    storage:
    - disk_size: 40906
      disk_thin_provisioned: true
  provisioners:
  - type: ansible
    playbook_file: rhel8/playbook.yml
    extra_arguments:
    - --extra-vars
    - "rhsm_username={{ rhsm.username }} rhsm_password={{ rhsm.password }} rhsm_pool_id={{ rhsm.pool_id }}"
    user: "{{ rhel8_ssh_username }}"
    ansible_env_vars:
    - ANSIBLE_HOST_KEY_CHECKING=False
    ssh_authorized_key_file: "{{ rhel8_ssh_pubkey_path }}"
    use_proxy: false
    only:
    - rhel8_vsphere_iso
